@echo off
set OPTION=

REM ON or OFF
set OPTION=%OPTION% -DBUILD_PYTHON_EXT=ON

REM Release or Debug
set OPTION=%OPTION% -DCMAKE_BUILD_TYPE=Release

REM ON or OFF
set OPTION=%OPTION% -DUSE_IJG_CODEC=OFF

REM ON or OFF
set OPTION=%OPTION% -DUSE_OPJ_CODEC=OFF

REM ON or OFF
set OPTION=%OPTION% -DUSE_DISPLAY_DEBUGINFO=ON

REM ON or OFF
set OPTION=%OPTION% -DBUILD_SHARED_LIBS=OFF

echo OPTIONS ARE =%OPTION%

cmake -G"NMake Makefiles" %OPTION% .